### PR TITLE
UCT/IB: Wrap calls to ibv_wc_status_str() from header files

### LINKED ISSUE #2859: Debug build on master, 1.4.x, and 1.3.x fails with undefined reference to symbol ibv_wc_status_str@@IBVERBS_1.1 error
When configured with `--enable-debug`, make fails with the following error:

```
  CCLD     ucx_info
/usr/bin/ld: ucx_info-type_info.o: undefined reference to symbol 'ibv_wc_status_str@@IBVERBS_1.1'
//usr/lib/libibverbs.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:526: recipe for target 'ucx_info' failed
make[3]: *** [ucx_info] Error 1
```

This occurs on master, v1.4.x, and v1.3.x.

I have only seen this on ubuntu-16.04, and only when configured with `--enable-debug`. In particular, it only occurs when compiling with `-O0`.  The problem does not show up when compiling with `-O1` or higher.  As for InfiniBand support, I see this with MOFED-4.3 and MOFED-4.4.

This looks similar to #2842, however, the LD_LIBRARY_PATH workaround that works
for it, does not work for this case.

### PR DESCRIPTION
**Pull request by yosefe**
- fixes #2859, need confirmation
- to be picked to v1.4.x

### CODE REVIEW

**Comment by hoopoepg** [comment]
@yosefe it seems ib_device.h should be included into rc_verbs_common.h

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7667/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7669/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@shamisp i am still not able to reproduce it on our Ubuntu test machines, so probably something is different with env/libtool/autotools that we use. I see Tony's libtool does not put UCT library dependencies in libuct.la, while on my system it does.
