### ISSUE TITLE
ucx 1.12.0 fails to compile with GCCcore 13.3.0

### ISSUE THREAD

**Issue by luciandf** [openucx/ucx#10610]
Hello all,

I have a bit of an odd problem and from the get go I have to apologize because my terminology is not that great but I'll try to be clear.

I am managing an HPC for my research needs and a small group of people and I have installed it in 2022 using recipes from openHPC. I manage the software with easybuild and mostly it has been ok apart from anything requiring UCX.

My system runs Rocky Linux 8.5 and right now I am unable to update to anything newer because the cluster is used continuously. My nodes use mellanox infiniband connectX5 and for some reason the only UCX version I am able to install via easybuild was 1.12.0. 

I have compiled UCX 1.12.0 with the foss2022 and foss2023 and intel2022 toolchains. Now I want to do the same with foss2024a toolchain but this time I get a new error that I have no idea how to handle:

```
In file included from debug/debug.c:27:
debug/debug.c: In function 'load_file':
debug/debug.c:277:53: error: 'PTR' undeclared (first use in this function)
  277 |     symcount = bfd_read_minisymbols(file->abfd, 0, (PTR)&file->syms, &size);
      |                                                     ^~~
/opt/ohpc/pub/thor/software/binutils/2.40-GCCcore-13.3.0/include/bfd.h:7292:30: note: in definition of macro 'BFD_SEND'
 7292 |   ((*((bfd)->xvec->message)) arglist)
      |                              ^~~~~~~
debug/debug.c:277:16: note: in expansion of macro 'bfd_read_minisymbols'
  277 |     symcount = bfd_read_minisymbols(file->abfd, 0, (PTR)&file->syms, &size);
      |                ^~~~~~~~~~~~~~~~~~~~
debug/debug.c:277:53: note: each undeclared identifier is reported only once for each function it appears in
  277 |     symcount = bfd_read_minisymbols(file->abfd, 0, (PTR)&file->syms, &size);
      |                                                     ^~~
/opt/ohpc/pub/thor/software/binutils/2.40-GCCcore-13.3.0/include/bfd.h:7292:30: note: in definition of macro 'BFD_SEND'
 7292 |   ((*((bfd)->xvec->message)) arglist)
      |                              ^~~~~~~
debug/debug.c:277:16: note: in expansion of macro 'bfd_read_minisymbols'
  277 |     symcount = bfd_read_minisymbols(file->abfd, 0, (PTR)&file->syms, &size);
      |                ^~~~~~~~~~~~~~~~~~~~
mv -f debug/.deps/libucs_la-assert.Tpo debug/.deps/libucs_la-assert.Plo
make[3]: *** [Makefile:1504: debug/libucs_la-debug.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/opt/ohpc/pub/thor/build/UCXGCCcore1330/1.12.0/GCCcore-13.3.0/ucx-1.12.0/src/ucs'
make[2]: *** [Makefile:1801: all-recursive] Error 1
make[2]: Leaving directory '/opt/ohpc/pub/thor/build/UCXGCCcore1330/1.12.0/GCCcore-13.3.0/ucx-1.12.0/src/ucs'
make[1]: *** [Makefile:743: all-recursive] Error 1
make[1]: Leaving directory '/opt/ohpc/pub/thor/build/UCXGCCcore1330/1.12.0/GCCcore-13.3.0/ucx-1.12.0'
make: *** [Makefile:610: all] Error 2
 (at easybuild/software/EasyBuild/4.9.4/lib/python3.6/site-packages/easybuild/tools/run.py:695 in parse_cmd_output)
== 2025-04-06 11:18:00,293 build_log.py:267 INFO ... (took 24 secs)
== 2025-04-06 11:18:00,293 filetools.py:2025 INFO Removing lock /opt/ohpc/pub/thor/software/.locks/_opt_ohpc_pub_thor_software_UCX-GCCcore-13.3.0_1.12.0-GCCcore-13.3.0.lock...
== 2025-04-06 11:18:00,355 filetools.py:385 INFO Path /opt/ohpc/pub/thor/software/.locks/_opt_ohpc_pub_thor_software_UCX-GCCcore-13.3.0_1.12.0-GCCcore-13.3.0.lock successfully removed.
== 2025-04-06 11:18:00,355 filetools.py:2029 INFO Lock removed: /opt/ohpc/pub/thor/software/.locks/_opt_ohpc_pub_thor_software_UCX-GCCcore-13.3.0_1.12.0-GCCcore-13.3.0.lock
== 2025-04-06 11:18:00,355 easyblock.py:4297 WARNING build failed (first 300 chars): cmd " make  -j 2 V=1" exited with exit code 2 and output:
make  all-recursive
make[1]: Entering directory '/opt/ohpc/pub/thor/build/UCXGCCcore1330/1.12.0/GCCcore-13.3.0/ucx-1.12.0'
Making all in src/ucm
make[2]: Entering directory '/opt/ohpc/pub/thor/build/UCXGCCcore1330/1.12.0/GCCcore-13.3.0/ucx-1.
== 2025-04-06 11:18:00,356 easyblock.py:326 INFO Closing log for application name UCX-GCCcore-13.3.0 version 1.12.0
```

Is there something I can do to overcome this?

P.S.: any other UCX version, although it installs, somehow it cannot work with mlnx5 infiniband driver. It doesn't recognise all the transport capabilities for some reason and any parallel jobs I send on my nodes fail. So until I am able to install the cluster from scratch with Rocky 9 and more updated drivers, I am a bit stuck.
