### ISSUE TITLE
Compilation failure with configure-devel on gcc 7.1.1

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1779]
UCX fails to compile with gcc 7.1.1 when compiled in devel mode.
The error happens in gtest so compiling with configure-release works.

Reproduces both on master and on the v1.2.x branch.

alinas@r-vmb-fedora26-x86-64-jb ~
$gcc --version
gcc (GCC) 7.1.1 20170622 (Red Hat 7.1.1-3)

alinas@r-vmb-fedora26-x86-64-jb ~
$cat /etc/redhat-release
Fedora release 26 (Twenty Six)

```
ucm/malloc_hook.cc: In member function âvoid test_thread::test()â:
ucm/malloc_hook.cc:260:23: error: âmalloc_get_stateâ was not declared in this scope
         void *state = malloc_get_state();
                       ^~~~~~~~~~~~~~~~
ucm/malloc_hook.cc:260:23: note: suggested alternative: âmalloc_statsâ
         void *state = malloc_get_state();
                       ^~~~~~~~~~~~~~~~
                       malloc_stats
ucm/malloc_hook.cc:261:9: error: âmalloc_set_stateâ was not declared in this scope
         malloc_set_state(state);
         ^~~~~~~~~~~~~~~~
ucm/malloc_hook.cc:261:9: note: suggested alternative: âmalloc_statsâ
         malloc_set_state(state);
         ^~~~~~~~~~~~~~~~
         malloc_stats
make[2]: *** [Makefile:1020: ucm/gtest-malloc_hook.o] Error 1
```

**Comment by alexander-sannikov** [comment]
For me master branch build fails for configure-devel and GCC 7.1.0 on tests with other symptoms:  

```
~> gcc --version
gcc (GCC) 7.1.0
~> V=1 make
... 
g++ -DHAVE_CONFIG_H -I. -I../..  -DCPU_FLAGS="" -I/opt/knem-1.1.2.90mlnx/include -I../../src -I../../test -I../../src -I../../test/gtest  -fopenmp   -O3 -g -Wall -Werror  -g -O3 -fno-tree-vectorize  -MT uct/ib/gtest-test_ud.o -MD -MP -MF uct/ib/.deps/gtest-test_ud.Tpo -c -o uct/ib/gtest-test_ud.o `test -f 'uct/ib/test_ud.cc' || echo './'`uct/ib/test_ud.cc
ucs/test_log.cc: In member function ‘virtual void log_test::init()’:
ucs/test_log.cc:14:18: error: ‘%s’ directive output may be truncated writing up to 63 bytes into a region of size 59 [-Werror=format-truncation=]
     virtual void init() {
                  ^~~~
ucs/test_log.cc:29:17: note: ‘snprintf’ output between 6 and 69 bytes into a destination of size 64
         snprintf(ucs_log_spec, sizeof(ucs_log_spec), "file:%s", logfile);
         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ucs/test_log.cc: In member function ‘virtual void log_test::_ZThn16_N8log_test4initEv()’:
ucs/test_log.cc:14:18: error: ‘%s’ directive output may be truncated writing up to 63 bytes into a region of size 59 [-Werror=format-truncation=]
     virtual void init() {
                  ^~~~
ucs/test_log.cc:29:17: note: ‘snprintf’ output between 6 and 69 bytes into a destination of size 64
         snprintf(ucs_log_spec, sizeof(ucs_log_spec), "file:%s", logfile);
         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by yosefe** [comment]
@alinask @hoopoepg was this fixed?

**Comment by alinask** [comment]
@yosefe no.

**Comment by alinask** [comment]
Fixed in https://github.com/openucx/ucx/pull/1826
