### ISSUE TITLE
Compilation fails when CFLAGS contains -Og

### ISSUE THREAD

**Issue by lyu** [openucx/ucx#7914]
### Describe the bug
As of d756ea0, UCX fails to compile with GCC 11.2.0 and `CFLAGS="-Og"`.

### Steps to Reproduce

`./configure CFLAGS="-Og" && make`
- UCX version d756ea0

### Setup and versions
- OS version: CentOS 8.1.1911 AArch64
- GCC 11.2.0

### Additional information (depending on the issue)
Error Message:
```
tcp/tcp_ep.c: In function 'uct_tcp_ep_ptr_map_get':
tcp/tcp_ep.c:200:9: error: 'ptr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  200 |         uct_tcp_ep_ptr_map_verify(ep, 1);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tcp/tcp_ep.c: In function 'uct_tcp_ep_ptr_map_retrieve':
tcp/tcp_ep.c:217:9: error: 'ptr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  217 |         uct_tcp_ep_ptr_map_removed(ep);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by dmitrygx** [comment]
@lyu thanks for discovering this issue!
is it possible to check whether #7932 helps to fix all compiler warnings or not?

**Comment by lyu** [comment]
@dmitrygx Thank you! #7932 fixes the issue and all warnings are gone, ucx installed successfully.

**Comment by dmitrygx** [comment]
> @dmitrygx Thank you! #7932 fixes the issue and all warnings are gone, ucx installed successfully.

great! thanks for your testing!
