### ISSUE TITLE
Build failed on master/v1.4.x with an error "undefined reference to `mlx5dv_init_obj'"

### ISSUE THREAD

**Issue by keisukefukuda** [openucx/ucx#2842]
Make fails on `master` and `v1.4.x` branch with the following error in my environment.

```
  CCLD     ucx_info
/home/kfukuda/ucx/src/uct/.libs/libuct.so: undefined reference to `mlx5dv_init_obj'
collect2: error: ld returned 1 exit status
Makefile:527: recipe for target 'ucx_info' failed
make[2]: *** [ucx_info] Error 1
```

The full logs are:
 * master: https://gist.github.com/keisukefukuda/f93b291921ae22baf7b2cc6e48f756f8
 * v1.4.x : https://gist.github.com/keisukefukuda/87e0c2531d2ed35621ae96a5a7286c55
 * v1.3.x : https://gist.github.com/keisukefukuda/df4c05c419ef25c0cd09c8d0355b5e41

while `v1.3.x ` branch builds successfully in the same environment and with the same configure options.

I'm working on Ubuntu 16.04 which is equipped with Infiniband FDR HCA, with the following mellanox-related packages installed.

```
$ dpkg -l | grep -i mlx
ii  libmlx4-1                                       41mlnx1-OFED.4.1.0.1.0.41102                            amd64        Userspace driver for Mellanox ConnectX InfiniBand HCAs
ii  libmlx4-dev                                     41mlnx1-OFED.4.1.0.1.0.41102                            amd64        Development files for the libmlx4 driver
ii  libmlx5-1                                       41mlnx1-OFED.4.1.0.1.5.41102                            amd64        Userspace driver for Mellanox ConnectX InfiniBand HCAs
ii  libmlx5-dev                                     41mlnx1-OFED.4.1.0.1.5.41102                            amd64        Development files for the libmlx5 driver
```

Is it a bug or any problem in my environment?
Please let me know if you need further information.

Thanks!

**Comment by brminich** [comment]
Probably libmlx5.so or/and libmlx5-rdmav2.so is missing. 
What does `ldd /home/kfukuda/ucx/src/uct/.libs/libuct.so` say?

**Comment by hoopoepg** [comment]
or libibverbs-dev package is missing

**Comment by shamisp** [comment]
@brminich @hoopoepg missing libraries should be detected by configure script and we should not fail during compilation - it is way too late to report missing library. IMHO mellanox verbs detection cofigury is broken and we should fix it.

**Comment by shamisp** [comment]
@yosefe - FYI

**Comment by shamisp** [comment]
BTW I don't think we have ubuntu in our testing - @keisukefukuda that a lot for catching this.

**Comment by brminich** [comment]
@shamisp, yes looks like a configure issue. Probably this can happen when mlx5dv.h is present but libmlx5 is not. Looks a bit strange, so we'd like to get more details about the configuration.

**Comment by shamisp** [comment]
@brminich - do we have any ubuntu boxes in regression ?

**Comment by brminich** [comment]
@shamisp, we have several virtual machines, but without any IB device configured

**Comment by keisukefukuda** [comment]
Thank you for your support, guys.

There are the configure logs.

master: https://gist.github.com/keisukefukuda/7742a8d51a00dd03ed5b24156bbfc982
v.1.3.x: https://gist.github.com/keisukefukuda/07953673a5ba7f30a09bebc855b998ee

@hoopoepg 
I checked if `libibverbs` packages are installed.
```
$ dpkg -l | grep libibverbs
ii  ibverbs-utils                                   41mlnx1-OFED.4.1.0.1.1.41102                            amd64        Examples for the libibverbs library
ii  libibverbs-dev                                  41mlnx1-OFED.4.1.0.1.1.41102                            amd64        Development files for the libibverbs library
ii  libibverbs1                                     41mlnx1-OFED.4.1.0.1.1.41102                            amd64        Library for direct userspace use of RDMA (InfiniBand/iWARP)
```
so `libibverbs-dev` is installed.


@brminich `ldd` says:
```
$ ldd /home/kfukuda/ucx/src/uct/.libs/libuct.so
	linux-vdso.so.1 =>  (0x00007ffdf3308000)
	libibverbs.so.1 => /usr/lib/libibverbs.so.1 (0x00002afed1808000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00002afed1a21000)
	libibcm.so.1 => /usr/lib/libibcm.so.1 (0x00002afed1c2c000)
	librdmacm.so.1 => /usr/lib/librdmacm.so.1 (0x00002afed1e31000)
	libcudart.so.9.2 => /usr/local/cuda/lib64/libcudart.so.9.2 (0x00002afed2048000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00002afed22b2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00002afed3232000)
	libucs.so.0 => /home/kfukuda/ucx/src/ucs/.libs/libucs.so.0 (0x00002afed353b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00002afed3778000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00002afed3995000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00002afed3b9d000)
	libnl-route-3.so.200 => /usr/lib/x86_64-linux-gnu/libnl-route-3.so.200 (0x00002afed3f67000)
	libnl-3.so.200 => /lib/x86_64-linux-gnu/libnl-3.so.200 (0x00002afed41ca000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00002afed43e9000)
	/lib64/ld-linux-x86-64.so.2 (0x00002afed1324000)
	libnvidia-fatbinaryloader.so.396.26 => /usr/lib/nvidia-396/libnvidia-fatbinaryloader.so.396.26 (0x00002afed45ed000)
	libucm.so.0 => /home/kfukuda/ucx/src/ucm/.libs/libucm.so.0 (0x00002afed4839000)
```

**Comment by yosefe** [comment]
@Artemy-Mellanox can you pls take a look? maybe something is missing from master

**Comment by keisukefukuda** [comment]
Forgot to mention that, as indicated by `ldd`, I could build it by 

```
export LD_LIBRARY_PATH=/usr/lib/libibverbs:$LD_LIBRARY_PATH
```
Although I'm not sure it is expected that `LD_LIBRARY_PATH` includes `/usr/lib/libverbs` in normal environment, I guess it should be taken care of in the  `configure` phase anyways.

**Comment by yosefe** [comment]
@Artemy-Mellanox need to check if mlx5dv_init_obj is used in any of the internal headers used by type_info.c, to reproduce need to remove deps from .la files

**Comment by shamisp** [comment]
@yosefe @Artemy-Mellanox : I think this is only the bug reports that holding of RC1 for v1.4.0. Do you have any update on this ?

**Comment by yosefe** [comment]
@keisukefukuda can you pls check if it works for you now with latest UCX master?

**Comment by keisukefukuda** [comment]
I checked and the problem was solved! :+1:
I'm closing the issue. Thanks a lot!
