### ISSUE TITLE
RoCM build failure with GDRCOPY 2.0 

### ISSUE THREAD

**Issue by bureddy** [openucx/ucx#4489]
```
01:28:44 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/0/contrib/../src/uct/rocm/gdr/rocm_gdr_ep.c: In function ‘uct_rocm_gdr_ep_put_short’:
01:28:44 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/0/contrib/../src/uct/rocm/gdr/rocm_gdr_ep.c:43:9: error: implicit declaration of function ‘gdr_copy_to_bar’ [-Werror=implicit-function-declaration]
01:28:44          ret = gdr_copy_to_bar((void *)remote_addr, buffer, length);
```

 @paklui @yuq  ROCM gdr_copy build is failing after upgrading nvidia gdr copy userspace to 2.0.  is RoCM expected to work with new NVIDIA gdrcopy userspace library?

**Comment by paklui** [comment]
We are using gdr copy 1.3 for now. I checked with @souravzzz and he is working in this area, he should have a fix about this soon.

**Comment by souravzzz** [comment]
Hi @bureddy rocm_gdr won't work with the new version of gdrcopy. We are planning to deprecate the rocm_gdr transport.

**Comment by paklui** [comment]
suggest asmall  correction in title: RoCM should be ROCm

**Comment by hongbilu** [comment]
i have a question. how does gdrcopy work with rocm, gdrdrv seems only support nvidia

**Comment by souravzzz** [comment]
@hongbilu gdrcopy is no longer required for rocm.
