### ISSUE TITLE
Compile: UCT ib_mlx5_dv fails on a particular machine

### ISSUE THREAD

**Issue by tonycurtis** [openucx/ucx#6311]
### Describe the bug

compile fails with missing macro

### Steps to Reproduce

github master @ 26ddfdd74aa6e3cd26896bf0010267aa97dfd50c

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

$ uname -a
Linux wombat-login2 4.18.0-147.el8.aarch64 #1 SMP Wed Dec 4 21:57:21 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

```

- For RDMA/IB/RoCE related issues:
        - or: MLNX_OFED version `ofed_info -s`

```
$ ofed_info -s
MLNX_OFED_LINUX-5.1-0.6.6.0:

```
 
### Additional information (depending on the issue)

`config.h` has

```
/* DC DV support */
/* #undef HAVE_DC_DV */

/* DC EXP support */
/* #undef HAVE_DC_EXP */
```

```
make[4]: Entering directory '/autofs/nccs-svm1_envoy_od/arcurtis/src/ucx/build/src/uct/ib'
  CC       mlx5/dv/libuct_ib_la-ib_mlx5_dv.lo
../../../../ucx-git/src/uct/ib/mlx5/dv/ib_mlx5_dv.c: In function ‘uct_ib_mlx5_devx_create_qp’:
../../../../ucx-git/src/uct/ib/mlx5/dv/ib_mlx5_dv.c:120:32: error: ‘UCT_IB_QPT_DCI’ undeclared (first use in this function); did you mean ‘UCT_IB_QPN_ORDER’?
  120 |     if (attr->super.qp_type == UCT_IB_QPT_DCI) {
      |                                ^~~~~~~~~~~~~~
      |                                UCT_IB_QPN_ORDER
../../../../ucx-git/src/uct/ib/mlx5/dv/ib_mlx5_dv.c:120:32: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [Makefile:1090: mlx5/dv/libuct_ib_la-ib_mlx5_dv.lo] Error 1
```

**Comment by yosefe** [comment]
probably introduced in #6290

**Comment by Artemy-Mellanox** [comment]
@tonycurtis could you plz provide entire config.h and config.log

**Comment by tonycurtis** [comment]
[config-h.txt](https://github.com/openucx/ucx/files/5962961/config-h.txt)
[config-log.txt](https://github.com/openucx/ucx/files/5962962/config-log.txt)

**Comment by Artemy-Mellanox** [comment]
@tonycurtis could you plz check whether fix https://github.com/openucx/ucx/pull/6314 solves
