### ISSUE TITLE
UCX 1.13.1 fails to build with verbs with gcc 11.2.0

### ISSUE THREAD

**Issue by mdorier** [openucx/ucx#8628]
### Describe the bug

I'm trying to build UCX using spack on Argonne's Polaris machine, with the `+verbs` variant. I'm using gcc 11.2.0, and compilation fails with the error bellow.

```
base/ib_md.c: In function 'uct_ib_cleanup':
/tmp/mdorier/spack-stage/spack-stage-ucx-1.13.1-xv2vjz55rtqujiyn4qzl4bg72ig2shk2/spack-src/src/ucs/sys/compiler_def.h:114:5: error: overflow in conversion from 'long unsigned int' to 'int' changes value from '18446744073709551615' to '-1' [-Werror=overflow]
  114 |     (sizeof(_array) / sizeof((_array)[0]))
      |     ^
base/ib_md.c:1858:14: note: in expansion of macro 'ucs_static_array_size'
 1858 |     for (i = ucs_static_array_size(uct_ib_tls) - 1; i >= 0; i--) {
      |
```

### Setup and versions

SUSE Linux Enterprise Server 15 SP3  (x86_64)
UCX 1.13.1

**Comment by hoopoepg** [comment]
hi @mdorier 
thank you for bug report.
can you try to build this PR: https://github.com/openucx/ucx/pull/8629

**Comment by mdorier** [comment]
Yes, that fixed the problem. Thanks!
