### ISSUE TITLE
UCX v1.2.2 failed to build with GCC 8.0.1

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2401]
Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1556515
Original Koji build (F28, doesn't contain logs): https://koji.fedoraproject.org/koji/taskinfo?taskID=24901110
Re-build (F29, with logs): https://koji.fedoraproject.org/koji/taskinfo?taskID=25717192

Reproduction:
1. Get the latest Fedora 28 or Rawhide. Or any other env with GCC 8.0.1.
2. Checkout `v1.2.2` tag.
3. `./autogen.sh && ./contrib/configure-release && make -j1`

GCC version:
```
gcc (GCC) 8.0.1 20180310 (Red Hat 8.0.1-0.17)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Build output:
```sh
...
  CC       debug/libucs_la-debug.lo
debug/debug.c: In function 'ucs_debug_lookup_address':
debug/debug.c:520:5: error: 'strncpy' specified bound 512 equals destination size [-Werror=stringop-truncation]
     strncpy(info->file.path, dlinfo.dli_fname, sizeof(info->file.path));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
debug/debug.c:522:5: error: 'strncpy' specified bound 128 equals destination size [-Werror=stringop-truncation]
     strncpy(info->function,
     ^~~~~~~~~~~~~~~~~~~~~~~
             (dlinfo.dli_sname != NULL) ? dlinfo.dli_sname : UCS_DEBUG_UNKNOWN_SYM,
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             sizeof(info->function));
             ~~~~~~~~~~~~~~~~~~~~~~~
debug/debug.c: In function 'ucs_debug_get_symbol_name':
debug/debug.c:589:17: error: 'strncpy' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
                 strncpy(sym, info.function, length + 1);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
debug/debug.c:586:22: note: length computed here
             length = strlen(info.function);
                      ^~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:1032: debug/libucs_la-debug.lo] Error 1
make[2]: Leaving directory '/tmp/ucx/src/ucs'
make[1]: *** [Makefile:649: all-recursive] Error 1
make[1]: Leaving directory '/tmp/ucx'
make: *** [Makefile:519: all] Error 2
```

Probably it is not the only issue, Fedora build log contains:
```sh
make[2]: Leaving directory '/builddir/build/BUILD/ucx-1.2.2/src/uct'
In file included from ib/ud/base/ud_ep.h:10,
                 from ib/ud/base/ud_ep.c:7:
ib/ud/base/ud_def.h:176:1: error: alignment 1 of 'struct uct_ud_send_skb_inl' is less than 64 [-Werror=packed-not-aligned]
 } UCS_S_PACKED uct_ud_send_skb_inl_t;
 ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:1406: ib/ud/base/libuct_la-ud_ep.lo] Error 1
```

**Comment by amaslenn** [comment]
`master` affected too.

**Comment by yosefe** [comment]
need to be fixed for master and v1.3.x

**Comment by shamisp** [comment]
indeed, so we up to rc4
