### ISSUE TITLE
build on ppc64 (be) on rhel 6.7

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#1624]
on `ah-rhel6-7-ppc64`
```
  CCLD     ucx_perftest
./.libs/libucxperf.a(libucxperf_la-uct_tests.o):(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: ld returned 1 exit status
make[2]: *** [ucx_perftest] Error 1
```
[ucx-1.2.2947.txt](https://github.com/openucx/ucx/files/1087845/ucx-1.2.2947.txt)
