### PR TITLE
TOOLS/INFO: Fix compiler warning

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix compiler warning in TOOLS/INFO code.

## Why ?

Introduced in #6267, but all checks were successful.
```
icc: command line warning #10148: option '-Wno-unused-label' not supported
icc: command line warning #10148: option '-Wno-format-zero-length' not supported
icc: command line warning #10148: option '-Wnested-externs' not supported
icc: command line warning #10148: option '-Wno-unused-label' not supported
icc: command line warning #10148: option '-Wno-format-zero-length' not supported
icc: command line warning #10148: option '-Wnested-externs' not supported
/scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/tools/info/proto_info.c(358): error #177: label "out_destroy_worker" was declared but never referenced
  out_destroy_worker:
```

## How ?

Remove unused goto's label `out_cleanup_context`.

### CODE REVIEW

**Review by rakhmets — APPROVED** [review]

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe @brminich ok to merge?

**Review by brminich — APPROVED** [review]
