### PR TITLE
UCP/UCT/UCS: Fix compiler warnings with -Og option

### LINKED ISSUE #7914: Compilation fails when CFLAGS contains -Og
### Describe the bug
As of d756ea0, UCX fails to compile with GCC 11.2.0 and `CFLAGS="-Og"`.

### Steps to Reproduce

`./configure CFLAGS="-Og" && make`
- UCX version d756ea0

### Setup and versions
- OS version: CentOS 8.1.1911 AArch64
- GCC 11.2.0

### Additional information (depending on the issue)
Error Message:
```
tcp/tcp_ep.c: In function 'uct_tcp_ep_ptr_map_get':
tcp/tcp_ep.c:200:9: error: 'ptr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  200 |         uct_tcp_ep_ptr_map_verify(ep, 1);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tcp/tcp_ep.c: In function 'uct_tcp_ep_ptr_map_retrieve':
tcp/tcp_ep.c:217:9: error: 'ptr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  217 |         uct_tcp_ep_ptr_map_removed(ep);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix compiler warnings with `-Og` option

## Why ?

Fixes #7914

## How ?

1. Set a pointer to pointer to `NULL` in places where it is required to suppress compiler warning.
2. Fix real issue in `ucp_ep_config_init` where `rsc_index` wasn't set to a proper value before calling `ucp_worker_iface_get_attr` for it.
3. Set all fields of `ucp_mem_map_params_t` to `0`, because the compiler thinks that `flags` filed could be used even if `field_mask == 0`.
4. Added compilation with `-Og` to our AZP CI's `builds.sh` script.

### CODE REVIEW

File: buildlib/tools/builds.sh [hunk 1]
```diff
@@ -244,6 +244,13 @@ build_clang() {
 # Build with gcc-latest module
 #
 build_gcc() {
+	if [ -z "$1" ]
```
Comment (yosefe) [inline buildlib/tools/builds.sh:247]: my not just "cflags=$1"

Comment (dmitrygx) [reply buildlib/tools/builds.sh]: done

File: buildlib/tools/builds.sh [hunk 2]
```diff
@@ -260,7 +262,7 @@ build_gcc() {
 		if az_module_load $GCC_MODULE
 		then
 			echo "==== Build with GCC compiler ($(gcc --version|head -1)) ===="
-			${WORKSPACE}/contrib/configure-devel --prefix=$ucx_inst
+			${WORKSPACE}/contrib/configure-devel CFLAGS=$cflags CXXFLAGS=$cflags --prefix=$ucx_inst
```
Comment (yosefe) [inline buildlib/tools/builds.sh:265]: BTW maybe use CFLAGS="$cflags" CXXFLAGS="$cflags" in case we pass multiple flags

**Review by yosefe — APPROVED** [review]
