### ISSUE TITLE
UCX fails to compile with GCC 13.1.0

### ISSUE THREAD

**Issue by cparrott73** [openucx/ucx#9058]
### Describe the bug
GCC 13.1.0 fails to compile the file `src/uct/base/uct_md.c`, failing with error due to `-Werror` being set on the command line.  Otherwise, the issue would be a warning:

base/uct_md.c:559:1: error: conflicting types for 'uct_md_mem_advise' due to enum/integer mismatch; have 'ucs_status_t(struct uct_md *, void *, void *, size_t,  unsigned int)' {aka 'ucs_status_t(struct uct_md *, void *, void *, long unsigned int,  unsigned int)'} [-Werror=enum-int-mismatch]
  559 | uct_md_mem_advise(uct_md_h md, uct_mem_h memh, void *addr, size_t length,
      | ^~~~~~~~~~~~~~~~~
In file included from base/uct_component.h:11,
                 from base/uct_md.h:14,
                 from base/uct_md.c:13:
/var/jenkins/workspace/gcc_lib_openmpi_x86_64/work/ucx-1.14.0/src/uct/api/uct.h:2542:14: note: previous declaration of 
'uct_md_mem_advise' with type 'ucs_status_t(struct uct_md *, void *, void *, size_t,  uct_mem_advice_t)' {aka 'ucs_status_t(struct uct_md *, void *, void *, long unsigned int,  uct_mem_advice_t)'}
 2542 | ucs_status_t uct_md_mem_advise(uct_md_h md, uct_mem_h memh, void *addr,
      |              ^~~~~~~~~~~~~~~~~
 

The issue here is that `uct_md_mem_advise()` is declared as `uct_md_mem_advise(uct_md_h, uct_mem_h, void *, size_t, uct_mem_advice_t)` in the `uct.h` header file, but in the `uct_md.c` file, the last parameter is declared as `unsigned` rather than `uct_mem_advice_t`.  GCC 13.1.0 now picks up on this discrepancy and flags it as a warning, which is elevated to an error when `-Werror` is passed to the compiler.

### Steps to Reproduce
- UCX version used: 1.14.0
- Steps to reproduce:

./configure CC=gcc CXX=g++
make

### Setup and versions
- OS version: Ubuntu 18.04 LTS
- CPU arch: x86_64

I have attached a patch which fixes the issue and allows UCX to compile with GCC 13.1.0 for me.

[ucx_gcc13.patch](https://github.com/openucx/ucx/files/11408164/ucx_gcc13.patch)

**Comment by changchengx** [comment]
Duplicated https://github.com/openucx/ucx/issues/8909
Fixed by https://github.com/openucx/ucx/pull/8804
