### ISSUE TITLE
[build] failed to build on ppc

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#3759]
Reproduced on ppc (`r-vmb-ppc-jenkins`), x86 is OK.

Cmd:
`./autogen.sh && ./contrib/configure-prof --prefix=$PWD/__install --without-java --with-knem --without-xpmem --without-java --enable-devel-headers --with-cuda=/hpc/local/oss/cuda10.1 --with-gdrcopy && make -j9`

```sh
Making all in .
make[3]: Entering directory `/auto/mtrswgwork/andreyma/ucx/src/uct'
  CC       base/libuct_la-uct_md.lo
  CC       base/libuct_la-uct_mem.lo
  CC       base/libuct_la-uct_component.lo
  CC       base/libuct_la-uct_iface.lo
  CC       base/libuct_la-uct_worker.lo
  CC       sm/base/libuct_la-sm_ep.lo
  CC       sm/base/libuct_la-sm_iface.lo
  CC       sm/mm/base/libuct_la-mm_iface.lo
  CC       sm/mm/base/libuct_la-mm_ep.lo
  CC       sm/mm/base/libuct_la-mm_md.lo
  CC       sm/mm/posix/libuct_la-mm_posix.lo
  CC       sm/mm/sysv/libuct_la-mm_sysv.lo
  CC       sm/self/libuct_la-self.lo
  CC       tcp/libuct_la-tcp_ep.lo
  CC       tcp/libuct_la-tcp_iface.lo
  CC       tcp/libuct_la-tcp_md.lo
  CC       tcp/libuct_la-tcp_net.lo
  CC       tcp/libuct_la-tcp_cm.lo
  CC       tcp/sockcm/libuct_la-sockcm_iface.lo
  CC       tcp/sockcm/libuct_la-sockcm_ep.lo
tcp/tcp_ep.c: In function ‘uct_tcp_ep_am_short’:
tcp/tcp_ep.c:735:32: error: ‘hdr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     memcpy((uint8_t*)(hdr + 1) + sizeof(header), payload, length);
                                ^
tcp/tcp_ep.c: In function ‘uct_tcp_ep_am_bcopy’:
tcp/tcp_ep.c:764:43: error: ‘hdr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     hdr->length = payload_length = pack_cb(hdr + 1, arg);
                                           ^
cc1: all warnings being treated as errors
make[3]: *** [tcp/libuct_la-tcp_ep.lo] Error 1
```

**Comment by yosefe** [comment]
@dmitrygladkov , is it fixed by #3753?

**Comment by dmitrygladkov** [comment]
> @dmitrygladkov , is it fixed by #3753?

@yosefe yes, #3753 fixes the issue
@amaslenn we added regression for this in #3753 PR, it passed. So, we can close this issue
