### ISSUE TITLE
Debug build on master, 1.4.x, and 1.3.x fails with undefined reference to symbol ibv_wc_status_str@@IBVERBS_1.1 error

### ISSUE THREAD

**Issue by bbenton** [openucx/ucx#2859]
When configured with `--enable-debug`, make fails with the following error:

```
  CCLD     ucx_info
/usr/bin/ld: ucx_info-type_info.o: undefined reference to symbol 'ibv_wc_status_str@@IBVERBS_1.1'
//usr/lib/libibverbs.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:526: recipe for target 'ucx_info' failed
make[3]: *** [ucx_info] Error 1
```

This occurs on master, v1.4.x, and v1.3.x.

I have only seen this on ubuntu-16.04, and only when configured with `--enable-debug`. In particular, it only occurs when compiling with `-O0`.  The problem does not show up when compiling with `-O1` or higher.  As for InfiniBand support, I see this with MOFED-4.3 and MOFED-4.4.

This looks similar to #2842, however, the LD_LIBRARY_PATH workaround that works
for it, does not work for this case.

**Comment by shamisp** [comment]
@hoopoepg @yosefe FYI

**Comment by yosefe** [comment]
I could not reproduce the issue with UCX master, Ubuntu 16.04, x86_64, and "--enable-debug"
@bbenton can you pls add the full output from "ofed_info" to see which RPMs are installed?
The contents of "config.log" and the output of "make V=1" could also help
BTW it's possible to attach files to github issue by drag&drop

**Comment by bbenton** [comment]
Here are the requested files:

[ofed_info.txt](https://github.com/openucx/ucx/files/2387014/ofed_info.txt)
[config.log](https://github.com/openucx/ucx/files/2387015/config.log)
[make-V1.txt](https://github.com/openucx/ucx/files/2387016/make-V1.txt)

**Comment by yosefe** [comment]
@bbenton can you pls check if #2863 fixes the issue?
BTW i still could not reproduce; seems like libtool on your setup does not put the dependencies into libucp.la/libuct.la

**Comment by bbenton** [comment]
@yosefe #2863 fixes the issue for me!
As for libtool, I noticed that it was not installed on my setup.  But, after installing it (v2.4.6), I re-built everything from scratch, but still see the failure with master.
